export const ERROR_CODES = {
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    ACCOUNT_NOT_APPROVED: "ACCOUNT_NOT_APPROVED",

    USER_NOT_FOUND: "USER_NOT_FOUND",
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

    STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",
    LECTURER_NOT_FOUND: "LECTURER_NOT_FOUND",
    STUDENT_ALREADY_EXISTS: "STUDENT_ALREADY_EXISTS",
    LECTURER_ALREADY_EXISTS: "LECTURER_ALREADY_EXISTS",
    
    COURSE_NOT_FOUND: "COURSE_NOT_FOUND",
    COURSE_FULL: "COURSE_FULL",
    COURSE_CLOSED: "COURSE_CLOSED",
    COURSE_ALREADY_EXISTS: "COURSE_ALREADY_EXISTS",

    ENROLLMENT_NOT_FOUND: "ENROLLMENT_NOT_FOUND",
    ALREADY_ENROLLED: "ALREADY_ENROLLED",
    ALREADY_WITHDRAWN: "ALREADY_WITHDRAWN",

    VALIDATION_ERROR: "VALIDATION_ERROR",

    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;