export const ERROR_CODES = {
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",

    USER_NOT_FOUND: "USER_NOT_FOUND",
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

    STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",
    LECTURER_NOT_FOUND: "LECTURER_NOT_FOUND",
    LECTURER_ALREADY_EXISTS: "LECTURER_ALREADY_EXISTS",

    VALIDATION_ERROR: "VALIDATION_ERROR",

    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;